<?php
/**
 * StoreAccountant
 * Export plugin for WooCommerce accounting workflows.
 *
 * @copyright   LaunchLab GmbH
 * @author      thomas.baier@launch-lab.de
 * @author-uri  https://launch-lab.de
 * @license     GPL-3.0-or-later
 */

declare(strict_types=1);

namespace StoreAccountant\Diagnostic\Admin;

use StoreAccountant\Contract\HookRegistrarInterface;
use StoreAccountant\Contract\WordPress\Request;
use StoreAccountant\Diagnostic\DiagnosticIncidentRepository;
use StoreAccountant\Security\Permission\PermissionActionIds;
use StoreAccountant\Security\Permission\PermissionChecker;
use function add_action;
use function check_admin_referer;
use function esc_html;
use function esc_html__;
use function header;
use function is_wp_error;
use function nocache_headers;
use function sprintf;
use function strlen;
use function wp_die;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Streams protected diagnostic incident files to authorized users.
 */
final readonly class DiagnosticIncidentDownloadController implements HookRegistrarInterface {
	public const ACTION = 'storeaccountant_download_diagnostic_incident';

	/**
	 * Initializes the controller.
	 *
	 * @param DiagnosticIncidentRepository $repository  Incident repository.
	 * @param PermissionChecker            $permissions Permission checker.
	 */
	public function __construct(
		private DiagnosticIncidentRepository $repository,
		private PermissionChecker $permissions
	) {}

	/**
	 * {@inheritDoc}
	 */
	public function register(): void {
		add_action( 'admin_post_' . self::ACTION, [ $this, 'handle' ] );
	}

	/**
	 * Handles the diagnostic incident download.
	 */
	public function handle(): void {
		if ( ! $this->permissions->can( PermissionActionIds::DIAGNOSTIC_PACKAGE_DOWNLOAD ) ) {
			wp_die( esc_html__( 'You are not allowed to download diagnostic packages.', 'storeaccountant' ) );
		}

		check_admin_referer( self::ACTION, '_wpnonce' );

		$support_id = Request::get_key( 'support_id' );
		$contents   = $this->repository->read( $support_id );

		if ( is_wp_error( $contents ) ) {
			wp_die( esc_html( $contents->get_error_message() ) );
		}

		nocache_headers();
		header( 'Content-Type: application/json; charset=utf-8' );
		header( sprintf( 'Content-Disposition: attachment; filename="storeaccountant-diagnostic-%s.json"', $support_id ) );
		header( 'Content-Length: ' . strlen( $contents ) );

		echo $contents; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- JSON file contents are generated by StoreAccountant and delivered as a download.
		exit;
	}
}
