services:
  php:
    image: storeaccountant-unit-php:${PHP_VERSION:-8.2}
    build:
      context: .
      dockerfile: Dockerfile-unit
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
    volumes:
      - .:/app
    working_dir: /app