<?php
/**
 * StoreAccountant
 * Export plugin for WooCommerce accounting workflows.
 *
 * @copyright   LaunchLab GmbH
 * @author      thomas.baier@launch-lab.de
 * @author-uri  https://launch-lab.de
 * @license     GPL-3.0-or-later
 */

declare(strict_types=1);

namespace StoreAccountant\Queue\Contract;

use StoreAccountant\Contract\RegistryItemInterface;
use Symfony\Component\Messenger\Transport\Serialization\SerializerInterface;
use Symfony\Component\Messenger\Transport\TransportInterface;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Defines a selectable Symfony Messenger queue transport provider.
 */
interface QueueTransportProviderInterface extends RegistryItemInterface {
	/**
	 * Gets the admin label for the transport.
	 */
	public function get_label(): string;

	/**
	 * Gets the admin description for the transport.
	 */
	public function get_description(): string;

	/**
	 * Gets the Symfony Messenger DSN generated by the provider.
	 */
	public function get_dsn(): string;

	/**
	 * Checks whether manual exports should kick off an async HTTP loopback runner.
	 */
	public function supports_manual_loopback(): bool;

	/**
	 * Creates the Symfony Messenger transport.
	 *
	 * @param SerializerInterface $serializer Messenger transport serializer.
	 */
	public function create_transport( SerializerInterface $serializer ): TransportInterface;
}
